version: "3.7"

services:
  flask:
    build: ./backend
    container_name: flask
    ports:
      - "8000:8000"

  react:
    build: ./frontend
    container_name: react
    ports:
      - "443:80"
      - "80:80"
